CREATE TABLE users (
id_db INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,

username VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
profileImage VARCHAR(2083) NOT NULL,

garuda INT DEFAULT 100,

rating INT DEFAULT NULL,
ranking INT DEFAULT 0,
phone_no BIGINT(20) DEFAULT 9999999999
)